# Generated by Django 5.1.2 on 2024-10-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ManyToManyField(blank=True, to='mainapp.uploadimage'),
        ),
    ]
