# Generated by Django 5.1.2 on 2024-10-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_resume_end_date_alter_resume_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
