# Generated by Django 5.1.2 on 2024-10-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_resume_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Resume Category',
                'db_table': 'Resume Category',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='category',
            field=models.ManyToManyField(blank=True, to='mainapp.resumecategory'),
        ),
    ]
