# Generated by Django 5.1.2 on 2024-10-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_resumecategory_resume_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='company_name',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.TextField(max_length=500),
        ),
    ]
