# Generated by Django 5.1.2 on 2024-10-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_resume_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
