# Generated by Django 5.1.2 on 2024-10-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
