# Generated by Django 5.1.2 on 2024-10-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_projects_github_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
