# Generated by Django 5.1.2 on 2024-11-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_delete_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='test_details',
            field=models.TextField(blank=True),
        ),
    ]
